version: '3.8'

services:
  discord_bot:
    image: lenqquisa/discord-bot:latest
    container_name: discord_bot_container
    restart: unless-stopped
    env_file: .env
    command: python3 bot.py
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    device_requests:
      - capabilities: [gpu]
